// Package wifi manages the hostapd subprocess for WiFi AP mode.
//
// It generates a hostapd.conf from the configuration, starts hostapd
// as a supervised child process, and parses its output for client
// association/disassociation events. The WiFi interface is bridged
// into br-lan by the caller after Start returns successfully.
package wifi

import (
	"bufio"
	"fmt"
	"io"
	"log"
	"os"
	"os/exec"
	"regexp"
	"strings"
	"sync"
	"text/template"

	"github.com/consolving/gokrazy-router/pkg/config"
)

const (
	confPath    = "/tmp/hostapd.conf"
	hostapdPath = "/usr/local/bin/hostapd"
)

// ClientEvent describes a WiFi client association or disassociation.
type ClientEvent struct {
	MAC        string
	Associated bool // true = associated, false = disassociated
}

// ClientCallback is called when a WiFi client connects or disconnects.
type ClientCallback func(event ClientEvent)

// AP manages the hostapd process.
type AP struct {
	cfg      config.WiFiConfig
	bridge   string
	cmd      *exec.Cmd
	onClient ClientCallback

	mu      sync.Mutex
	clients map[string]bool // MAC -> associated
}

var confTemplate = template.Must(template.New("hostapd").Parse(`# Generated by gokrazy-router
interface={{.Interface}}
bridge={{.Bridge}}
driver=nl80211
ssid={{.SSID}}
hw_mode={{.HWMode}}
channel={{.Channel}}
{{- if .CountryCode}}
country_code={{.CountryCode}}
ieee80211d=1
{{- end}}
{{- if .HTCapab}}
ieee80211n=1
ht_capab={{.HTCapab}}
{{- else}}
ieee80211n=1
{{- end}}
wmm_enabled=1
wds_sta=1
ap_isolate=0

# WPA2-PSK
wpa={{.WPA}}
wpa_passphrase={{.Passphrase}}
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP

# Logging: enable all module messages to stdout
logger_stdout=-1
logger_stdout_level=2
`))

// New creates a new AP manager. bridge is the bridge to add wlan0 to
// (hostapd handles bridging itself via the bridge= directive in config).
func New(cfg config.WiFiConfig, bridge string) (*AP, error) {
	if cfg.SSID == "" {
		return nil, fmt.Errorf("wifi: SSID must not be empty")
	}
	if cfg.Passphrase == "" {
		return nil, fmt.Errorf("wifi: passphrase must not be empty")
	}
	if len(cfg.Passphrase) < 8 || len(cfg.Passphrase) > 63 {
		return nil, fmt.Errorf("wifi: WPA2 passphrase must be 8-63 characters")
	}

	// Apply defaults.
	if cfg.Interface == "" {
		cfg.Interface = "wlan0"
	}
	if cfg.HWMode == "" {
		cfg.HWMode = "g" // 2.4 GHz
	}
	if cfg.Channel == 0 {
		cfg.Channel = 6
	}
	if cfg.WPA == 0 {
		cfg.WPA = 2
	}

	return &AP{
		cfg:     cfg,
		bridge:  bridge,
		clients: make(map[string]bool),
	}, nil
}

// OnClient registers a callback for client association/disassociation events.
func (ap *AP) OnClient(cb ClientCallback) {
	ap.onClient = cb
}

// Start generates the config and launches hostapd. It returns once hostapd
// has started (or fails). The caller should run this in a goroutine if
// they want non-blocking startup.
func (ap *AP) Start() error {
	// Write hostapd.conf.
	data := struct {
		config.WiFiConfig
		Bridge string
	}{
		WiFiConfig: ap.cfg,
		Bridge:     ap.bridge,
	}

	f, err := os.Create(confPath)
	if err != nil {
		return fmt.Errorf("wifi: create config: %w", err)
	}
	if err := confTemplate.Execute(f, data); err != nil {
		f.Close()
		return fmt.Errorf("wifi: write config: %w", err)
	}
	f.Close()

	log.Printf("wifi: wrote %s (ssid=%s iface=%s channel=%d)", confPath, ap.cfg.SSID, ap.cfg.Interface, ap.cfg.Channel)

	// Start hostapd.
	ap.cmd = exec.Command(hostapdPath, confPath)
	ap.cmd.Env = os.Environ()

	// Capture stdout+stderr for log parsing.
	stdout, err := ap.cmd.StdoutPipe()
	if err != nil {
		return fmt.Errorf("wifi: stdout pipe: %w", err)
	}
	ap.cmd.Stderr = ap.cmd.Stdout // merge stderr into stdout

	if err := ap.cmd.Start(); err != nil {
		return fmt.Errorf("wifi: start hostapd: %w", err)
	}

	log.Printf("wifi: hostapd started (pid=%d)", ap.cmd.Process.Pid)

	// Parse output in background.
	go ap.parseOutput(stdout)
	go ap.wait()

	return nil
}

// Stop terminates the hostapd process.
func (ap *AP) Stop() {
	if ap.cmd != nil && ap.cmd.Process != nil {
		log.Printf("wifi: stopping hostapd")
		ap.cmd.Process.Signal(os.Interrupt)
	}
}

// Clients returns the list of currently associated client MACs.
func (ap *AP) Clients() []string {
	ap.mu.Lock()
	defer ap.mu.Unlock()
	var macs []string
	for mac, assoc := range ap.clients {
		if assoc {
			macs = append(macs, mac)
		}
	}
	return macs
}

// Regexes to match hostapd log lines for client events.
// hostapd logs: "wlan0: STA aa:bb:cc:dd:ee:ff IEEE 802.11: associated"
// hostapd logs: "wlan0: STA aa:bb:cc:dd:ee:ff IEEE 802.11: disassociated"
// Also: "AP-STA-CONNECTED aa:bb:cc:dd:ee:ff" and "AP-STA-DISCONNECTED aa:bb:cc:dd:ee:ff"
var (
	reAssociated    = regexp.MustCompile(`STA ([0-9a-f:]{17}).*associated`)
	reDisassociated = regexp.MustCompile(`STA ([0-9a-f:]{17}).*disassociated`)
	reConnected     = regexp.MustCompile(`AP-STA-CONNECTED ([0-9a-f:]{17})`)
	reDisconnected  = regexp.MustCompile(`AP-STA-DISCONNECTED ([0-9a-f:]{17})`)
)

func (ap *AP) parseOutput(r io.Reader) {
	scanner := bufio.NewScanner(r)
	for scanner.Scan() {
		line := scanner.Text()
		// Always log hostapd output.
		log.Printf("hostapd: %s", line)

		// Check for client events.
		if m := reConnected.FindStringSubmatch(line); m != nil {
			ap.handleEvent(ClientEvent{MAC: strings.ToLower(m[1]), Associated: true})
		} else if m := reDisconnected.FindStringSubmatch(line); m != nil {
			ap.handleEvent(ClientEvent{MAC: strings.ToLower(m[1]), Associated: false})
		} else if m := reAssociated.FindStringSubmatch(line); m != nil {
			// Only fire if it's not a "disassociated" line
			if !reDisassociated.MatchString(line) {
				ap.handleEvent(ClientEvent{MAC: strings.ToLower(m[1]), Associated: true})
			}
		}
		if m := reDisassociated.FindStringSubmatch(line); m != nil {
			ap.handleEvent(ClientEvent{MAC: strings.ToLower(m[1]), Associated: false})
		}
	}
}

func (ap *AP) handleEvent(ev ClientEvent) {
	ap.mu.Lock()
	ap.clients[ev.MAC] = ev.Associated
	ap.mu.Unlock()

	action := "connected"
	if !ev.Associated {
		action = "disconnected"
	}
	log.Printf("wifi: client %s %s", ev.MAC, action)

	if ap.onClient != nil {
		ap.onClient(ev)
	}
}

func (ap *AP) wait() {
	err := ap.cmd.Wait()
	if err != nil {
		log.Printf("wifi: hostapd exited: %v", err)
	} else {
		log.Printf("wifi: hostapd exited cleanly")
	}
}
