// Package wifi manages the hostapd subprocess for WiFi AP mode.
//
// It generates a hostapd.conf from the configuration, starts hostapd
// as a supervised child process, and parses its output for client
// association/disassociation events.
//
// Two modes are supported:
//   - Bridged: hostapd config includes bridge=<name>, wlan0 is added to the
//     bridge automatically. Requires driver support for AP+bridge.
//   - Routed (default): wlan0 gets its own subnet and IP. A separate DHCP
//     server should be started on wlan0. This works with all drivers.
package wifi

import (
	"bufio"
	"fmt"
	"io"
	"log"
	"os"
	"os/exec"
	"regexp"
	"strings"
	"sync"
	"text/template"
	"time"

	"github.com/consolving/gokrazy-router/pkg/config"
)

const (
	confPath    = "/tmp/hostapd.conf"
	hostapdPath = "/usr/local/bin/hostapd"
)

// ClientEvent describes a WiFi client association or disassociation.
type ClientEvent struct {
	MAC        string
	Associated bool // true = associated, false = disassociated
}

// ClientCallback is called when a WiFi client connects or disconnects.
type ClientCallback func(event ClientEvent)

const (
	// Backoff parameters for hostapd restarts.
	initialBackoff = 1 * time.Second
	maxBackoff     = 30 * time.Second
	// If hostapd runs longer than this, the backoff resets.
	stableRunTime = 10 * time.Second
)

// AP manages the hostapd process.
type AP struct {
	cfg      config.WiFiConfig
	bridge   string // empty = routed mode
	cmd      *exec.Cmd
	onClient ClientCallback

	mu      sync.Mutex
	clients map[string]bool // MAC -> associated

	stopOnce sync.Once
	stopCh   chan struct{} // closed when Stop() is called
}

var confTemplate = template.Must(template.New("hostapd").Parse(`# Generated by gokrazy-router
interface={{.Interface}}
{{- if .Bridge}}
bridge={{.Bridge}}
{{- end}}
driver=nl80211
ssid={{.SSID}}
hw_mode={{.HWMode}}
channel={{.Channel}}
{{- if .CountryCode}}
country_code={{.CountryCode}}
ieee80211d=1
{{- end}}
{{- if .HTCapab}}
ieee80211n=1
ht_capab={{.HTCapab}}
{{- else}}
ieee80211n=1
{{- end}}
wmm_enabled=1

# WPA2-PSK
wpa={{.WPA}}
wpa_passphrase={{.Passphrase}}
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP

# Logging: enable all module messages to stdout
logger_stdout=-1
logger_stdout_level=2
`))

// New creates a new AP manager. bridge may be empty for routed mode.
func New(cfg config.WiFiConfig, bridge string) (*AP, error) {
	if cfg.SSID == "" {
		return nil, fmt.Errorf("wifi: SSID must not be empty")
	}
	if cfg.Passphrase == "" {
		return nil, fmt.Errorf("wifi: passphrase must not be empty")
	}
	if len(cfg.Passphrase) < 8 || len(cfg.Passphrase) > 63 {
		return nil, fmt.Errorf("wifi: WPA2 passphrase must be 8-63 characters")
	}

	// Apply defaults.
	if cfg.Interface == "" {
		cfg.Interface = "wlan0"
	}
	if cfg.HWMode == "" {
		cfg.HWMode = "g" // 2.4 GHz
	}
	if cfg.Channel == 0 {
		cfg.Channel = 6
	}
	if cfg.WPA == 0 {
		cfg.WPA = 2
	}

	return &AP{
		cfg:     cfg,
		bridge:  bridge,
		clients: make(map[string]bool),
		stopCh:  make(chan struct{}),
	}, nil
}

// OnClient registers a callback for client association/disassociation events.
func (ap *AP) OnClient(cb ClientCallback) {
	ap.onClient = cb
}

// Start generates the config and launches hostapd with automatic restart
// on crash. It returns once the first hostapd instance has started (or fails).
// If hostapd exits unexpectedly, it is restarted with exponential backoff.
func (ap *AP) Start() error {
	if err := ap.writeConfig(); err != nil {
		return err
	}

	if err := ap.launch(); err != nil {
		return err
	}

	// Supervise in background: restart on crash with backoff.
	go ap.supervise()

	return nil
}

// writeConfig generates the hostapd.conf file.
func (ap *AP) writeConfig() error {
	data := struct {
		config.WiFiConfig
		Bridge string
	}{
		WiFiConfig: ap.cfg,
		Bridge:     ap.bridge,
	}

	f, err := os.Create(confPath)
	if err != nil {
		return fmt.Errorf("wifi: create config: %w", err)
	}
	if err := confTemplate.Execute(f, data); err != nil {
		f.Close()
		return fmt.Errorf("wifi: write config: %w", err)
	}
	f.Close()

	mode := "routed"
	if ap.bridge != "" {
		mode = "bridged (" + ap.bridge + ")"
	}
	log.Printf("wifi: wrote %s (ssid=%s iface=%s channel=%d mode=%s)", confPath, ap.cfg.SSID, ap.cfg.Interface, ap.cfg.Channel, mode)
	return nil
}

// launch starts a new hostapd process.
func (ap *AP) launch() error {
	ap.cmd = exec.Command(hostapdPath, confPath)
	ap.cmd.Env = os.Environ()

	stdout, err := ap.cmd.StdoutPipe()
	if err != nil {
		return fmt.Errorf("wifi: stdout pipe: %w", err)
	}
	ap.cmd.Stderr = ap.cmd.Stdout // merge stderr into stdout

	if err := ap.cmd.Start(); err != nil {
		return fmt.Errorf("wifi: start hostapd: %w", err)
	}

	log.Printf("wifi: hostapd started (pid=%d)", ap.cmd.Process.Pid)

	go ap.parseOutput(stdout)

	return nil
}

// supervise waits for hostapd to exit and restarts it with exponential
// backoff unless Stop() was called.
func (ap *AP) supervise() {
	backoff := initialBackoff

	for {
		started := time.Now()
		err := ap.cmd.Wait()

		// Check if we were asked to stop.
		select {
		case <-ap.stopCh:
			if err != nil {
				log.Printf("wifi: hostapd exited during shutdown: %v", err)
			} else {
				log.Printf("wifi: hostapd exited cleanly")
			}
			return
		default:
		}

		if err != nil {
			log.Printf("wifi: hostapd crashed: %v", err)
		} else {
			log.Printf("wifi: hostapd exited unexpectedly with status 0")
		}

		// Reset backoff if the process ran long enough to be considered stable.
		if time.Since(started) >= stableRunTime {
			backoff = initialBackoff
		}

		// Clear client list on crash.
		ap.mu.Lock()
		ap.clients = make(map[string]bool)
		ap.mu.Unlock()

		log.Printf("wifi: restarting hostapd in %v", backoff)

		select {
		case <-time.After(backoff):
		case <-ap.stopCh:
			log.Printf("wifi: stop requested, not restarting hostapd")
			return
		}

		// Increase backoff for next crash.
		backoff *= 2
		if backoff > maxBackoff {
			backoff = maxBackoff
		}

		if err := ap.launch(); err != nil {
			log.Printf("wifi: failed to restart hostapd: %v", err)
			// Continue the loop — we'll retry after the next backoff.
			continue
		}
	}
}

// Stop terminates the hostapd process and prevents automatic restart.
func (ap *AP) Stop() {
	ap.stopOnce.Do(func() {
		close(ap.stopCh)
	})
	if ap.cmd != nil && ap.cmd.Process != nil {
		log.Printf("wifi: stopping hostapd")
		ap.cmd.Process.Signal(os.Interrupt)
	}
}

// Clients returns the list of currently associated client MACs.
func (ap *AP) Clients() []string {
	ap.mu.Lock()
	defer ap.mu.Unlock()
	var macs []string
	for mac, assoc := range ap.clients {
		if assoc {
			macs = append(macs, mac)
		}
	}
	return macs
}

// Regexes to match hostapd log lines for client events.
var (
	reAssociated    = regexp.MustCompile(`STA ([0-9a-f:]{17}).*associated`)
	reDisassociated = regexp.MustCompile(`STA ([0-9a-f:]{17}).*disassociated`)
	reConnected     = regexp.MustCompile(`AP-STA-CONNECTED ([0-9a-f:]{17})`)
	reDisconnected  = regexp.MustCompile(`AP-STA-DISCONNECTED ([0-9a-f:]{17})`)
)

func (ap *AP) parseOutput(r io.Reader) {
	scanner := bufio.NewScanner(r)
	for scanner.Scan() {
		line := scanner.Text()
		// Always log hostapd output.
		log.Printf("hostapd: %s", line)

		// Check for client events.
		if m := reConnected.FindStringSubmatch(line); m != nil {
			ap.handleEvent(ClientEvent{MAC: strings.ToLower(m[1]), Associated: true})
		} else if m := reDisconnected.FindStringSubmatch(line); m != nil {
			ap.handleEvent(ClientEvent{MAC: strings.ToLower(m[1]), Associated: false})
		} else if m := reAssociated.FindStringSubmatch(line); m != nil {
			if !reDisassociated.MatchString(line) {
				ap.handleEvent(ClientEvent{MAC: strings.ToLower(m[1]), Associated: true})
			}
		}
		if m := reDisassociated.FindStringSubmatch(line); m != nil {
			ap.handleEvent(ClientEvent{MAC: strings.ToLower(m[1]), Associated: false})
		}
	}
}

func (ap *AP) handleEvent(ev ClientEvent) {
	ap.mu.Lock()
	ap.clients[ev.MAC] = ev.Associated
	ap.mu.Unlock()

	action := "connected"
	if !ev.Associated {
		action = "disconnected"
	}
	log.Printf("wifi: client %s %s", ev.MAC, action)

	if ap.onClient != nil {
		ap.onClient(ev)
	}
}

